"""Collect a bounded, redacted repository context without network access."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
import os
from pathlib import Path
import re
import subprocess
from typing import Iterable, Sequence

from . import __version__


DEFAULT_EXCLUDED_DIRS = {
    ".git",
    ".hg",
    ".svn",
    "node_modules",
    "vendor",
    "dist",
    "build",
    "coverage",
    ".venv",
    "venv",
    "__pycache__",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    ".codex",
}

SENSITIVE_BASENAMES = {
    ".env",
    ".env.local",
    ".env.production",
    ".env.development",
    "id_rsa",
    "id_dsa",
    "id_ecdsa",
    "id_ed25519",
    "credentials.json",
    "credentials.yml",
    "credentials.yaml",
    "service-account.json",
}

SENSITIVE_SUFFIXES = {".pem", ".p12", ".pfx", ".key", ".jks"}
SENSITIVE_NAME_RE = re.compile(
    r"(?:^|[-_.])(secret|secrets|credential|credentials|passwords?|tokens?)(?:[-_.]|$)",
    re.IGNORECASE,
)

LANGUAGE_BY_SUFFIX = {
    ".c": "c",
    ".cc": "cpp",
    ".cpp": "cpp",
    ".cs": "csharp",
    ".css": "css",
    ".go": "go",
    ".h": "c",
    ".hpp": "cpp",
    ".html": "html",
    ".java": "java",
    ".js": "javascript",
    ".jsx": "javascript",
    ".json": "json",
    ".md": "markdown",
    ".php": "php",
    ".py": "python",
    ".rb": "ruby",
    ".rs": "rust",
    ".scss": "scss",
    ".sh": "shell",
    ".sql": "sql",
    ".svg": "xml",
    ".toml": "toml",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".vue": "vue",
    ".xml": "xml",
    ".yaml": "yaml",
    ".yml": "yaml",
}

IMPORTANT_FILENAMES = {
    "README",
    "README.md",
    "LICENSE",
    "Dockerfile",
    "Makefile",
    "Cargo.toml",
    "go.mod",
    "package.json",
    "pyproject.toml",
    "requirements.txt",
    "SKILL.md",
}


@dataclass(frozen=True)
class FileContext:
    """A safe, bounded representation of one repository file."""

    path: str
    size: int
    language: str
    excerpt: str | None = None
    excerpt_truncated: bool = False


@dataclass
class RepositoryContext:
    """Repository metadata and selected file excerpts for a planning request."""

    root: Path
    branch: str | None
    status: list[str]
    recent_commits: list[str]
    files: list[FileContext]
    excluded_sensitive: list[str] = field(default_factory=list)
    omitted_files: int = 0
    generated_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    @property
    def repository_name(self) -> str:
        return self.root.name or str(self.root)

    def to_markdown(self) -> str:
        """Render the context in a human-readable, pasteable Markdown format."""

        lines = [
            "# Repository Context",
            "",
            f"Generated by Codex Pro Planning Bridge {__version__}.",
            "This context was collected locally; no repository content was uploaded.",
            "",
            "## Repository",
            "",
            f"- Name: `{self.repository_name}`",
            f"- Branch: `{self.branch or 'unavailable'}`",
            f"- Generated at: `{self.generated_at.isoformat()}`",
            "",
            "## Git Status",
            "",
        ]

        if self.status:
            lines.extend(f"- `{item}`" for item in self.status)
        else:
            lines.append("- Working tree clean or Git metadata unavailable.")

        lines.extend(["", "## Recent Commits", ""])
        if self.recent_commits:
            lines.extend(f"- {commit}" for commit in self.recent_commits)
        else:
            lines.append("- No commit history available.")

        lines.extend(
            [
                "",
                "## File Inventory",
                "",
                "| Path | Size | Language | Excerpt |",
                "| --- | ---: | --- | --- |",
            ]
        )
        for file_context in self.files:
            excerpt_state = "yes" if file_context.excerpt is not None else "no"
            path = file_context.path.replace("|", "\\|")
            lines.append(
                f"| `{path}` | {file_context.size} | "
                f"{file_context.language} | {excerpt_state} |"
            )

        if self.omitted_files:
            lines.extend(
                [
                    "",
                    f"{self.omitted_files} additional files were omitted because the "
                    "configured file limit was reached.",
                ]
            )

        lines.extend(["", "## Redaction Notes", ""])
        if self.excluded_sensitive:
            lines.append(
                "Sensitive-looking files were excluded from content excerpts: "
                + ", ".join(f"`{path}`" for path in self.excluded_sensitive)
                + "."
            )
        else:
            lines.append("No sensitive-looking files were discovered.")

        lines.extend(["", "## Selected Excerpts", ""])
        excerpt_files = [file_context for file_context in self.files if file_context.excerpt]
        if not excerpt_files:
            lines.append("No text excerpts were selected.")
        else:
            for file_context in excerpt_files:
                lines.extend(
                    [
                        f"### `{file_context.path}`",
                        "",
                        f"~~~{file_context.language}",
                        file_context.excerpt.rstrip(),
                        "~~~",
                        "",
                    ]
                )
                if file_context.excerpt_truncated:
                    lines.append("_Excerpt truncated by the configured byte limit._")
                    lines.append("")

        return "\n".join(lines).rstrip() + "\n"


def is_sensitive_path(path: str | Path) -> bool:
    """Return whether a relative path looks like it may contain a secret."""

    path_obj = Path(path)
    basename = path_obj.name.lower()
    if basename in {item.lower() for item in SENSITIVE_BASENAMES}:
        return True
    if path_obj.suffix.lower() in SENSITIVE_SUFFIXES:
        return True
    if any(part.lower() in {"secret", "secrets", "credentials", "private"} for part in path_obj.parts):
        return True
    return bool(SENSITIVE_NAME_RE.search(path_obj.stem))


def _run_git(root: Path, args: Sequence[str]) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(root), *args],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=5,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def _git_file_paths(root: Path) -> list[str] | None:
    output = _run_git(root, ["ls-files", "--cached", "--others", "--exclude-standard"])
    if output is None:
        return None
    return [line.replace("\\", "/") for line in output.splitlines() if line.strip()]


def _fallback_file_paths(root: Path, include_hidden: bool) -> list[str]:
    paths: list[str] = []
    for current, directories, filenames in os.walk(root, followlinks=False):
        current_path = Path(current)
        directories[:] = sorted(
            directory
            for directory in directories
            if directory not in DEFAULT_EXCLUDED_DIRS
            and (include_hidden or not directory.startswith("."))
        )
        for filename in sorted(filenames):
            if not include_hidden and filename.startswith(".") and not is_sensitive_path(filename):
                continue
            full_path = current_path / filename
            try:
                relative = full_path.relative_to(root).as_posix()
            except ValueError:
                continue
            paths.append(relative)
    return paths


def _language_for(path: str) -> str:
    name = Path(path).name
    if name == "Dockerfile":
        return "dockerfile"
    if name in {"Makefile", "justfile"}:
        return "makefile"
    return LANGUAGE_BY_SUFFIX.get(Path(path).suffix.lower(), "text")


def _priority(path: str) -> tuple[int, str]:
    name = Path(path).name
    if name in IMPORTANT_FILENAMES:
        return (0, path)
    if path.startswith("docs/") or "/docs/" in path:
        return (1, path)
    return (2, path)


def _read_excerpt(path: Path, max_bytes: int) -> tuple[str | None, bool]:
    try:
        raw = path.read_bytes()
    except OSError:
        return None, False
    if b"\x00" in raw[:4096]:
        return None, False
    truncated = len(raw) > max_bytes
    raw = raw[:max_bytes]
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        text = raw.decode("utf-8", errors="replace")
    return text.replace("\r\n", "\n"), truncated


def _redact_status_line(line: str) -> str:
    path_part = line[3:].strip() if len(line) >= 3 else line
    if is_sensitive_path(path_part):
        return line[:2] + " [sensitive path omitted]"
    return line


def collect_repository(
    root: str | Path = ".",
    *,
    max_files: int = 80,
    max_file_bytes: int = 12_000,
    max_total_bytes: int = 120_000,
    include_hidden: bool = False,
) -> RepositoryContext:
    """Collect repository metadata and bounded, redacted file excerpts.

    The collector never makes network calls. Git metadata is read with local
    commands when available; a filesystem walk is used for non-Git directories.
    """

    if max_files < 1:
        raise ValueError("max_files must be at least 1")
    if max_file_bytes < 1 or max_total_bytes < 1:
        raise ValueError("excerpt byte limits must be positive")

    root_path = Path(root).expanduser().resolve()
    if not root_path.is_dir():
        raise ValueError(f"repository path is not a directory: {root_path}")

    git_paths = _git_file_paths(root_path)
    file_paths = git_paths if git_paths else _fallback_file_paths(root_path, include_hidden)
    file_paths = sorted(set(file_paths), key=_priority)

    excluded_sensitive: list[str] = []
    candidates: list[tuple[str, Path, int]] = []
    for relative in file_paths:
        if is_sensitive_path(relative):
            if len(excluded_sensitive) < 20:
                excluded_sensitive.append(relative)
            continue
        full_path = root_path / Path(relative)
        try:
            if not full_path.is_file():
                continue
            size = full_path.stat().st_size
        except OSError:
            continue
        candidates.append((relative, full_path, size))

    selected = candidates[:max_files]
    omitted_files = max(0, len(candidates) - len(selected))
    files: list[FileContext] = []
    excerpt_bytes = 0
    for relative, full_path, size in selected:
        language = _language_for(relative)
        excerpt: str | None = None
        excerpt_truncated = False
        if language in set(LANGUAGE_BY_SUFFIX.values()) | {"dockerfile", "makefile"}:
            remaining = max_total_bytes - excerpt_bytes
            if remaining > 0:
                excerpt, excerpt_truncated = _read_excerpt(
                    full_path, min(max_file_bytes, remaining)
                )
                if excerpt is not None:
                    excerpt_bytes += len(excerpt.encode("utf-8"))
        files.append(
            FileContext(
                path=relative,
                size=size,
                language=language,
                excerpt=excerpt,
                excerpt_truncated=excerpt_truncated,
            )
        )

    branch = _run_git(root_path, ["branch", "--show-current"])
    if branch == "":
        branch = _run_git(root_path, ["rev-parse", "--short", "HEAD"])
    status_output = _run_git(root_path, ["status", "--short", "--untracked-files=all"])
    status = [_redact_status_line(line) for line in (status_output or "").splitlines()]
    recent_output = _run_git(root_path, ["log", "-5", "--pretty=format:%h %s"])
    recent_commits = (recent_output or "").splitlines()

    return RepositoryContext(
        root=root_path,
        branch=branch or None,
        status=status,
        recent_commits=recent_commits,
        files=sorted(files, key=lambda item: item.path),
        excluded_sensitive=sorted(excluded_sensitive),
        omitted_files=omitted_files,
    )
